### PR TITLE
feat: support darwin arm64

### PR DESCRIPTION
**Pull request by sutt0n**

### CODE REVIEW

**Comment by sutt0n** [comment]
Anyone from @bluemill able to review and approve this?

**Comment by sutt0n** [comment]
cc: @kyleferguson (since you're the only publicly available member for the org).

**Comment by jiggyjigsj** [comment]
@kyleferguson @sutt0n Is it possible to release this to Terraform Registry?

**Comment by sutt0n** [comment]
@kyleferguson could we get a re-release of this to the TF registry please?

**Pull request merged**
